# 测试环境，外部用户无法访问，专门给测试人员使用的，版本相对稳定
spring:
  # 应用名称
  application:
    name: wandring
  # SpringBoot 2.6.0开始使用基于PathPatternParser的路径匹配，而Springfox版本一直没有更新还是使用的AntPathMatcher
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER